version: 2.1

jobs:
  #DEBIAN
  job-0-debian:
    docker:
      - image: "debian:latest"
    steps:
      - checkout
      - run:
          name: Update and install sudo
          command: "apt-get update && apt-get install -y sudo &&  rm -rf /var/lib/apt/lists/* "
      - run:
          name: install qqy
          command: apt-get update -qqy && apt-get -qqy install
      - run:
          name: Install the required dev packages
          command: "apt-get install -yqq g++ python python3"
      - run:
          name: install git
          command: apt-get install -yqq git
      - run:
          name: install cmake
          command: apt-get install -yqq cmakeF

workflows:
  version: 2.1
  start-containers:
    jobs:
      - job-0-debian
