version: 2.1

jobs:
  # UBUNTU
  job-1-ubuntu:
    docker:
      - image: "ubuntu:latest"
    steps:
      - checkout
      - run:
          name: "set env vars again"
          command: |
            echo 'debconf debconf/frontend select Noninteractive' debconf-set-selections
            echo export DEBIAN_FRONTEND=noninteractive >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Update and install sudo
          command: "apt-get update && apt-get install -y sudo &&  rm -rf /var/lib/apt/lists/* "
      - run:
          name: install qqy
          command: apt-get update -qqy && apt-get -qqy install
      - run:
          name: Install the required packages
          command: "apt-get install -yqq g++ python python3"
      - run:
          name: install git
          command: apt-get install -yqq git
      - run:
          name: install cmake
          command: apt-get install -yqq cmake

workflows:
  version: 2.1
  start-containers:
    jobs:
      - job-1-ubuntu
